name: check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCLANG_FORMAT_PATH=/usr/local/bin/clang-format

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j6

    - name: Format Check
      run: cmake --build ${{github.workspace}}/build --target format_check

    - name: Compile Testcases
      run: python3 ./scripts/run_all.py --fuzz no-func-inline --fuzz no-opt

    - name: Set Run Token
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1

    - name: Push Intermediates to Raspberry Pi
      uses: appleboy/scp-action@master
      with:
        host: localhost
        username: pi
        password: ${{ secrets.PASSWORD }}
        port: 2004
        source: "testcases,scripts/test_all.py"
        target: github-action/${{ steps.generate-uuid.outputs.uuid }}
        proxy_host: 140.143.248.164
        proxy_password: ${{ secrets.PASSWORD }}
        proxy_username: helesta 
      
    - name: Run Testcases
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/scripts/test_all.py --testcase_path /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/testcases

    - name: Benchmark
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/scripts/test_all.py --testcase_path /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/testcases --benchmark --benchmark_summary_path /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/summary.md

    - name: Pull Benchmark Summary From Raspberry Pi
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      uses: nicklasfrahm/scp-action@main
      with:
        direction: download
        host: localhost
        username: pi
        insecure_password: ${{ secrets.PASSWORD }}
        port: 2004
        source: /home/pi/github-action/${{ steps.generate-uuid.outputs.uuid }}/summary.md
        target: "summary.md"
        proxy_host: ${{ secrets.HOST }}
        insecure_proxy_password: ${{ secrets.PASSWORD }}
        insecure_proxy_ignore_fingerprint: true
        insecure_ignore_fingerprint: true
        proxy_username: helesta 

    - name: Post Summary
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      run: cat summary.md >> $GITHUB_STEP_SUMMARY
