name: check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j6

    - name: Format Check
      run: cmake --build ${{github.workspace}}/build --target format_check

    - name: Compile Testcases
      run: python3 ./scripts/run_all.py

    - name: Archive Compile Results
      uses: actions/upload-artifact@v3
      with:
        name: compile-results
        path: testcases
      
    - name: Run Testcases
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: whoami
