name: check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j6

    - name: Format Check
      run: cmake --build ${{github.workspace}}/build --target format_check

    - name: Compile Testcases
      run: python3 ./scripts/run_all.py

    - name: Push Intermediates to Raspberry Pi
      uses: nicklasfrahm/scp-action@main
      with:
        direction: upload
        host: localhost
        username: pi
        insecure_password: ${{ secrets.PASSWORD }}
        port: 2004
        source: "testcases,scripts/test_all.py"
        target: "github-action"
        proxy_host: ${{ secrets.HOST }}
        insecure_proxy_password: ${{ secrets.PASSWORD }}
        proxy_username: helesta 
      
    - name: Run Testcases
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/scripts/test_all.py --testcase_path /home/pi/github-action/testcases

    - name: Benchmark
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/scripts/test_all.py --testcase_path /home/pi/github-action/testcases --benchmark

    - name: Pull Benchmark Summary From Raspberry Pi
      uses: nicklasfrahm/scp-action@main
      with:
        direction: download
        host: localhost
        username: pi
        insecure_password: ${{ secrets.PASSWORD }}
        port: 2004
        source: "/home/pi/github-action/summary.md"
        target: "summary.md"
        proxy_host: ${{ secrets.HOST }}
        insecure_proxy_password: ${{ secrets.PASSWORD }}
        proxy_username: helesta 

    - name: Post Summary
      run: echo summary.md >> $GITHUB_STEP_SUMMARY
