name: Sanity Check
on: [push]

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"

    - name: Configure CMake
      run: cmake -DCLANG_FORMAT_EXE=${{ env.LLVM_PATH }}/bin/clang-format -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}/bin/clang++ -B ${{github.workspace}}/build

    - name: Format Check
      run: cmake --build ${{github.workspace}}/build --target format_check

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j6

    - name: Compile Testcases
      run: python3 ./scripts/run_all.py --fuzz no-func-inline --fuzz no-opt

    - uses: actions/upload-artifact@v3
      with:
        name: asms-ins-outs
        path: ./testcases

  push-to-raspberry-pi:
    runs-on: ubuntu-latest
    needs: build-and-format

    steps:
    - name: Gen Run Token
      id: generate-uuid
      uses: filipstefansson/uuid-action@v1

    - name: Set Run Token to Env
      run: echo "RUN_ID=${{ steps.generate-uuid.outputs.uuid }}" >> $GITHUB_ENV

    - name: Pull Artifatcs
      uses: actions/download-artifact@v3
      with:
        name: asms-ins-outs
        path: ./testcases

    - name: Push Intermediates to Raspberry Pi
      uses: appleboy/scp-action@master
      with:
        host: localhost
        username: pi
        password: ${{ secrets.PASSWORD }}
        port: 2004
        source: "testcases,scripts/test_all.py"
        target: github-action/${{ env.RUN_ID }}
        proxy_host: 140.143.248.164
        proxy_password: ${{ secrets.PASSWORD }}
        proxy_username: helesta 

  run-on-raspberry-pi:
    runs-on: ubuntu-latest
    concurrency: raspberry
    needs: push-to-raspberry-pi
    
    steps:
    - name: Run Testcases
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/${{ env.RUN_ID }}/scripts/test_all.py --testcase_path /home/pi/github-action/${{ env.RUN_ID }}/testcases

    - name: Benchmark
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/${{ env.RUN_ID }}/scripts/test_all.py --testcase_path /home/pi/github-action/${{ env.RUN_ID }}/testcases --benchmark --benchmark_summary_path /home/pi/github-action/${{ env.RUN_ID }}/summary.md

    - name: Pull Benchmark Summary From Raspberry Pi
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      uses: nicklasfrahm/scp-action@main
      with:
        direction: download
        host: localhost
        username: pi
        insecure_password: ${{ secrets.PASSWORD }}
        port: 2004
        source: /home/pi/github-action/${{ env.RUN_ID }}/summary.md
        target: "summary.md"
        proxy_host: ${{ secrets.HOST }}
        insecure_proxy_password: ${{ secrets.PASSWORD }}
        insecure_proxy_ignore_fingerprint: true
        insecure_ignore_fingerprint: true
        proxy_username: helesta 

    - name: Post Summary
      if: ${{ contains(github.event.head_commit.message, '$bench') }}  
      run: cat summary.md >> $GITHUB_STEP_SUMMARY
