name: check
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j6

    - name: Format Check
      run: cmake --build ${{github.workspace}}/build --target format_check

    - name: Compile Testcases
      run: python3 ./scripts/run_all.py

    - name: Send Results to Raspberry Pi
      uses: appleboy/scp-action@master
      with:
        host: localhost
        username: pi
        password: ${{ secrets.PASSWORD }}
        port: 2004
        source: "testcases,scripts/test_all.py"
        target: "github-action"
        proxy_host: 140.143.248.164
        proxy_password: ${{ secrets.PASSWORD }}
        proxy_username: helesta 
      
    - name: Run Testcases
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: python3 /home/pi/github-action/test_all.py --testcase_path /home/pi/github-action/testcases
